### ISSUE TITLE
MaxTransferHopCountExceeded - what is it?

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#21]
DLQ documentation lists the reasons why a message can end up in a DLQ.
One of the reasons is `MaxTransferHopCountExceeded` ("Maximum transfer hop count is exceeded.").

There's also a "Dead-lettering in ForwardTo or SendVia scenarios" section states that 
> A message passes through more than 3 queues or topics that are chained together.

will be sent to the **TDLQ**, not the **DLQ**.

So what is the number of maximum allowed hops when forwarding between queues?

**Comment by SeanFeldman** [comment]
@sethmanheim @jtaubensee any ideas?

**Comment by jtaubensee** [comment]
@SeanFeldman - So to clarify, you are suggesting that this article: https://github.com/Microsoft/azure-docs/blob/master/articles/service-bus-messaging/service-bus-dead-letter-queues.md

Should be cleaned up a bit to state that you will get an error like this `MaxTransferHopCountExceeded`?

**Comment by SeanFeldman** [comment]
@jtaubensee That article should be reviewed indeed.

For example, what the following stands for?
![image](https://cloud.githubusercontent.com/assets/1309622/25813790/225ba128-33d8-11e7-8891-f92842177070.png)

Condition(`!dead letter queue`) is cryptic.
`DeadLetterReason` is good, but no clarity that it will take 3 hops (forwards) to get this error.

**Comment by SeanFeldman** [comment]
Also

> A message passes through more than 3 queues or topics that are chained together.

This is too generalized. If this is not part of send-via and a transaction, the message will end up in a normal DLQ, not a TDLQ.

**Comment by sethmanheim** [comment]
Not clear what documentation fixes are needed here.

**Comment by SeanFeldman** [comment]
@sethmanheim given [this comment](https://github.com/Azure/azure-service-bus/issues/21#issuecomment-299589646) and potentially incorrect info in this [doco section](https://github.com/Azure/azure-service-bus/issues/21#issuecomment-299918100) don't think this issue should be closed until doco is clarified and updated.

**Comment by sethmanheim** [comment]
I closed it because I opened an internal bug to track. But sure, let's keep it open if you prefer, I'll try to keep it updated.

**Comment by sethmanheim** [comment]
Oh and yes, I was planning on doing that with some of the other open issues too, but having some technical issues.

**Comment by SeanFeldman** [comment]
> I closed it because I opened an internal bug to track

Unfortunately for the outside world it looks as the issue is addressed (and hence is closed) w/o seeing any changes 🙂 
Also, would be great if the doco changes/PR would be tied to this issue. Then anyone who's interested in this issue and subscribed to it could either help or chime in and help drive the questions/answers.

**Comment by sethmanheim** [comment]
Per my earlier comment, still not clear what the documentation fixes are here. Please clarify.

**Comment by SeanFeldman** [comment]
![image](https://user-images.githubusercontent.com/1309622/36124825-d522ec90-100e-11e8-875f-2b336054e9a9.png)

What `!dead letter queue` means?

**Comment by SeanFeldman** [comment]
Coming back to this issue - the topic of max hops really needs some love.

**Comment by axisc** [comment]
this has been fixed on the document [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#moving-messages-to-the-dlq)
