### ISSUE TITLE
PartitionKey vs TransactionPartitionKey 

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-service-bus#558]
What's the purpose of [TransactionPartitionKey](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage.transactionpartitionkey?view=azure-dotnet)? The documentation is very confusing and not clear.

In the past, for send-via/transactional processing, we needed to set the PartitionKey of the outgoing messages to the [PartitionKey](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage.partitionkey?view=azure-dotnet) of the incoming message. Does TransactionPartitionKey replace that requirement or need to be set in addition to PartitionKey? And if these two are equivalent, why does ServiceBusReceivedMessage expose both? 

PS: the [article](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions) about transactional processing doesn't mention anything partitions related. It probably should.

**Comment by SeanFeldman** [comment]
@EldertGrootenboer, I hope your search for the information is yielding promising results and it's just WIP until something is posted 🙂

**Comment by EldertGrootenboer** [comment]
We had some internal discussion about this, but looking at the remarks section we think this is already addressed?

_If a message is sent via a transfer queue in the scope of a transaction, this value selects the transfer queue partition: This is functionally equivalent to [PartitionKey](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage.partitionkey?view=azure-dotnet#azure-messaging-servicebus-servicebusreceivedmessage-partitionkey) and ensures that messages are kept together and in order as they are transferred. See [Transfers and Send Via](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions#transfers-and-send-via)._

As specified, it will work in the scope of a transaction, and otherwise is functionally the same as [PartitionKey](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage.partitionkey?view=azure-dotnet#azure-messaging-servicebus-servicebusreceivedmessage-partitionkey).

As for the article about transactional processing, we will update this to include a reference to this.

**Comment by yvesgoeleven** [comment]
What happens to a group of messages, when in a scope, while PartitionKey is set and TransactionPartitionKey is not?

The messages can still get out of order while in the transfer queue?

**Comment by EldertGrootenboer** [comment]
Thank you for your feedback. We have brought this item in our current semester, and should be able to provide an update in the coming months.

**Comment by EldertGrootenboer** [comment]
We have update the [documentation](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-transactions) to indicate that if a message is sent via a transfer queue in the scope of a transaction, `TransactionPartitionKey` is functionally equivalent to `PartitionKey`. It ensures that messages are kept together and in order as they are transferred.
